output: docs
author: gematik GmbH
author_url: http://www.gematik.de
exclude: /*/internal*
#module: OpenHealthCardKit
github_url: https://www.github.com/gematik/ref-openhealthcardkit
theme: jony
swift_build_tool: xcodebuild
xcodebuild_arguments:
  - "-project"
  - 'OpenHealthCardKit.xcodeproj'
  - "-scheme"
  - 'Documentation'
