name: OpenHealthCardKit
options:
  bundleIdPrefix: de.gematik.ti.openhealthcard
  deploymentTarget:
    macOS: 10.14
    iOS: 13.0
settings:
  base:
    CODE_SIGN_IDENTITY: ""
    SWIFT_VERSION: 5.0
    ALWAYS_SEARCH_USER_PATHS: NO
    FRAMEWORK_SEARCH_PATHS: "$(inherited)"
  configs:
    Release:
      SWIFT_COMPILATION_MODE: wholemodule
    Debug:
      SWIFT_COMPILATION_MODE: incremental
targets:
  CardReaderProviderApi:
    type: framework
    platform: [iOS,macOS]
    sources:
      - Sources/CardReaderProviderApi
    info:
      path: Resources/CardReaderProviderApi_Info.plist
    dependencies:
      - carthage: GemCommonsKit
    scheme:
      testTargets:
        - CardReaderProviderApiTests_${platform}
      gatherCoverageData: true
  CardReaderAccess:
    type: framework
    platform: [iOS,macOS]
    sources:
      - Sources/CardReaderAccess
    info:
      path: Resources/CardReaderAccess_Info.plist
    dependencies:
      - target: CardReaderProviderApi_${platform}
    scheme:
      testTargets:
        - CardReaderAccessTests_${platform}
      gatherCoverageData: true
  CardReaderProviderApiTests:
    type: bundle.unit-test
    platform: [macOS,iOS]
    info:
      path: Resources/CardReaderProviderApiTests_Info.plist
    sources:
      - Tests/CardReaderProviderApiTests
    dependencies:
      - target: CardReaderProviderApi_${platform}
      - carthage: Nimble
  CardReaderAccessTests:
    type: bundle.unit-test
    platform: [macOS,iOS]
    info:
      path: Resources/CardReaderAccessTests_Info.plist
    sources:
      - Tests/CardReaderAccessTests
    dependencies:
      - target: CardReaderAccess_${platform}
      - carthage: Nimble
  HealthCardAccess:
    type: framework
    platform: [macOS,iOS]
    info:
      path: Resources/HealthCardAccess_Info.plist
    sources:
      - Sources/HealthCardAccess
    dependencies:
      - target: CardReaderAccess_${platform}
      - target: CardReaderProviderApi_${platform}
      - carthage: ASN1Kit
      - carthage: DataKit
    transitivelyLinkDependencies: true
    scheme:
      testTargets:
        - HealthCardAccessTests_${platform}
      gatherCoverageData: true
  HealthCardAccessTests:
    type: bundle.unit-test
    platform: [macOS,iOS]
    info:
      path: Resources/HealthCardAccessTests_Info.plist
    sources:
      - path: Tests/HealthCardAccessTests
      - path: Tests/Util
    dependencies:
      - target: HealthCardAccess_${platform}
      - carthage: ObjCCommonsKit
      - carthage: Nimble
  HealthCardControl:
    type: framework
    platform: [iOS,macOS]
    info:
      path: Resources/HealthCardControl_Info.plist
    sources:
      - path: Sources/HealthCardControl
    dependencies:
      - target: HealthCardAccess_${platform}
      - carthage: BigInt
    transitivelyLinkDependencies: true
    scheme:
      testTargets:
        - HealthCardControlTests_${platform}
      gatherCoverageData: true
  HealthCardControlTests:
    name: HealthCardControlTests_${platform}
    type: bundle.unit-test
    platform: [macOS,iOS]
    info:
      path: Resources/HealthCardControlTests_Info.plist
    sources:
      - path: Tests/HealthCardControlTests
      - path: Tests/Util
    dependencies:
      - target: HealthCardControl_${platform}
      - carthage: Nimble
  NFCCardReaderProvider:
    type: framework
    platform: iOS
    info:
      path: Resources/NFCCardReaderProvider_Info.plist
    sources:
      - Sources/NFCCardReaderProvider
    dependencies:
      - target: HealthCardAccess_iOS
      - sdk: CoreNFC.framework
    scheme:
      testTargets:
        - NFCCardReaderProviderTests
      gatherCoverageData: true
  NFCCardReaderProviderTests:
    type: bundle.unit-test
    platform: iOS
    info:
      path: Resources/NFCCardReaderProviderTests_Info.plist
    sources:
      - Tests/NFCCardReaderProviderTests
    dependencies:
      - target: NFCCardReaderProvider
      - carthage: Nimble
  Documentation:
    type: framework
    platform: macOS
    info:
      path: Resources/Documentation_Info.plist
    settings:
      # PRODUCT_NAME becomes the Documentation/Module title
      PRODUCT_NAME: "OpenHealthCardKit"
      SWIFT_OBJC_BRIDGING_HEADER: ${SRCROOT}/BridgeHeader.h
    sources:
      - path: Sources/CardReaderAccess
      - path: Sources/CardReaderProviderApi
      - path: Sources/HealthCardAccess
      - path: Sources/HealthCardControl
      - path: Sources/NFCCardReaderProvider
    scheme:
    dependencies:
      - carthage: BigInt
      - carthage: DataKit
      - carthage: ASN1Kit
      - carthage: GemCommonsKit
buildImplicitDependencies: true
