#!/bin/sh

# scripts/bootstrap: Resolve all dependencies that the application requires to
#                   run.

set -ev

cd "$(dirname "$0")/.."

if [ -f "Brewfile" ] && [ "$(uname -s)" = "Darwin" ]; then
  brew bundle check >/dev/null 2>&1  || {
    echo "==> Installing Homebrew dependencies…"
    brew bundle
  }
else
  hash swiftlint 2>/dev/null  || {
    echo "==> Installing swiftlint…"
    brew install gematik/tap/swiftlint
  }
  hash xcodegen 2>/dev/null  || {
    echo "==> Installing xcodegen…"
    brew install gematik/tap/xcodegen
  }
fi

if [ -f "Gemfile" ]; then
  hash bundle 2>/dev/null || {
    echo "==> Installing Bundler 2.0.1…"
    gem install bundler -v 2.0.1 --no-document --quiet
  }
  echo "==> Installing gem dependencies…"
  bundle check --path vendor/gems >/dev/null 2>&1  || {
    bundle install --path vendor/gems --quiet --without production
  }
fi

if [ -f "Cartfile" ]; then
  hash carthage 2>/dev/null || {
    echo "==> Installing gematik/tap/carthage…"
    brew install gematik/tap/carthage
  }
fi
