[#NFCCardReaderProvider]
=== NFCCardReaderProvider

A `CardReaderProvider` implementation that handles the
communication with the Apple iPhone NFC interface.

==== NFCCardReaderSession

For convience, the `NFCCardReaderSession` combines the usage of the NFC inteface with the `HealthCardAccess/HealthCardControl` layers.

The initializer takes some NFC-Display messages, the CAN (card access number) and a closure with a `NFCHealthCardSessionHandle` to send/receive commands/responses to/from the NFC HealthCard and to update the user's interface message to.

[source,swift]
----
include::{sourcedir}/NFCDemo/NFC/NFCLoginController.swift[tags=nfcHealthCardSession_init,indent=0]
----

Execute the operation on the NFC HealthCard. The secure channel (PACE) is established initially before executing the operation.

[source,swift]
----
include::{sourcedir}/NFCDemo/NFC/NFCLoginController.swift[tags=nfcHealthCardSession_execute,indent=0]
----

The thrown error will be of type `NFCHealthCardSessionError`.
The `NFCHealthCardSession` also gives you an endpoint to invalidate the underlying `TagReaderSession`.

[source,swift]
----
include::{sourcedir}/NFCDemo/NFC/NFCLoginController.swift[tags=nfcHealthCardSession_errorHandling,indent=0]
----