[#HealthCardControl]
=== HealthCardControl

This library can be used to realize use cases for interacting with a German Health Card
(eGk, elektronische Gesundheitskarte) via a mobile device.

Typically you would use this library as the high level API gateway for your mobile application
to send predefined command chains to the Health Card and interpret the responses.

For more info, please find the low level part `HealthCardAccess`.
and a https://github.com/gematik/ref-OpenHealthCardApp-iOS[Demo App] on GitHub.

See the https://gematik.github.io/[Gematik GitHub IO] page for a more general overview.


==== Code Samples

Take the necessary preparatory steps for signing a challenge on the Health Card, then sign it.

[source,swift]
----
include::{integrationtestdir}/HealthCardControl/HealthCardTypeExtESIGNIntegrationTest.swift[tags=signChallenge,indent=0]
----


Encapsulate the https://www.bsi.bund.de/DE/Publikationen/TechnischeRichtlinien/tr03110/index_htm.html[PACE protocol]
steps for establishing a secure channel with the Health Card and expose only a simple API call .

[source,swift]
----
include::{integrationtestdir}/HealthCardControl/KeyAgreementIntegrationTest.swift[tags=negotiateSessionKey,indent=0]
----

See the integration tests link:include::{integrationtestdir}/HealthCardControl/[IntegrationTests/HealthCardControl/]
for more already implemented use cases.